defaults:
  - user: user2
  - corridor_parameter: corridor1

hydra:
  run:
    dir: ${user.run_dir}

device: "cuda"
seed: 123

nn_plant:
  dt: 0.1
  hidden_layers: [8, 4]

policy:
  wandb:
    enabled: ${user.wandb_enabled}
    project: score_po
    dir: ${user.run_dir}
    name: ${now:%Y.%m.%d-%H.%M.%S}_corridor_path
    entity: ${user.wandb_entity}
  T: 40
  x0_upper: ${x_start}
  x0_lower: ${x_start}
  batch_size: 1
  std: 0.
  lr: 1e-3
  max_iters: 1000
  save_best_model: ${user.save_optimal_path}
  device: ${device}
  load_ckpt: ${user.load_optimal_path}
  beta: 1


x_start: [0, 1]
x_goal: [1, 0]

corridor_width: ${corridor_parameter.corridor_width}
horizontal_max: ${corridor_parameter.horizontal_max}
vertical_max: ${corridor_parameter.vertical_max}
u_lo: ${corridor_parameter.u_lo}
u_up: ${corridor_parameter.u_up}

dynamics_load_ckpt: ${user.dynamics_load_ckpt}
score_estimator_load_ckpt: ${user.score_estimator_load_ckpt}
