run_dir: /home/hongkaidai/score_po_data/corridor/${now:%Y-%m-%d}/${now:%H-%M-%S}

dataset_load_path: /home/hongkaidai/score_po_data/corridor/2023-04-25/12-17-34/dataset/dataset.pth

wandb_enabled: True
wandb_entity: daihongkai

dynamics_load_ckpt: /home/hongkaidai/score_po_data/corridor/2023-04-25/12-17-34/checkpoint/checkpoint.pth
save_score_ckpt: ${user.run_dir}/score/checkpoint.pth
score_estimator_load_ckpt: /home/hongkaidai/score_po_data/corridor/2023-04-25/20-49-01/score/checkpoint.pth
save_optimal_path: ${user.run_dir}/optimal_path/checkpoint.pth
load_optimal_path: null