run_dir: /home/terry/Documents/score_po_data/d4rl/

wandb_enabled: True
wandb_entity: hjsuh94
env_name: halfcheetah-medium-expert-v2

cost_weights: /home/terry/Documents/score_po_data/d4rl/checkpoint_cost_${env_name}.pth
dynamics_weights: /home/terry/Documents/score_po_data/d4rl/checkpoint_dynamics_${env_name}.pth
score_weights: /home/terry/Documents/score_po_data/d4rl/checkpoint_score_${env_name}.pth
policy_weights: /home/terry/Documents/score_po_data/d4rl/checkpoint_policy_${env_name}.pth