run_dir: /home/hongkaidai/Dropbox/score_po_data/cartpole/${now:%Y-%m-%d}/${now:%H-%M-%S}

# This dataset has size 100,000
dataset_load_path: /home/hongkaidai/Dropbox/score_po_data/cartpole/2023-05-27/16-23-34/dataset/dataset.pth
# This dataset has size 1,000,000
# dataset_load_path: /home/hongkaidai/Dropbox/score_po_data/cartpole/2023-04-28/11-43-31/dataset/dataset.pth
# This dataset has size 4,000,000
# dataset_load_path: /home/hongkaidai/score_po_data/cartpole/2023-05-02/12-35-16/dataset/dataset.pth

wandb_enabled: True
wandb_entity: daihongkai

# dynamics_load_ckpt: /home/hongkaidai/Dropbox/score_po_data/cartpole/2023-04-28/11-43-31/checkpoint/checkpoint.pth
# This dynamics model is trained together with the dataset with 100,000 samples.
dynamics_load_ckpt: /home/hongkaidai/Dropbox/score_po_data/cartpole/2023-05-27/16-23-34/checkpoint/checkpoint.pth
load_swingup_trj: null # /home/hongkaidai/Dropbox/score_po_data/cartpole/2023-04-28/19-14-20/swingup_openloop_policy.pth
save_swingup_trj: swingup_trj.pth
save_score_ckpt: score/checkpoint.pth
save_dde_ckpt: dde/dde_checkpoint.pth
score_estimator_xu_load_ckpt: /home/hongkaidai/Dropbox/score_po_data/cartpole/2023-04-29/16-11-51/score/checkpoint.pth
score_estimator_xux_load_ckpt: /home/hongkaidai/Dropbox/score_po_data/cartpole/2023-05-02/23-25-38/score/checkpoint.pth
dde_xu_load_ckpt: /home/hongkaidai/Dropbox/score_po_data/cartpole/2023-05-27/17-14-17/dde/dde_checkpoint.pth