run_dir: ~/Documents/score_po_data/cartpole/${now:%Y-%m-%d}/${now:%H-%M-%S}

dataset_load_path: ~/Documents/score_po_data/cartpole/dataset.pth

wandb_enabled: True
wandb_entity: null

save_swingup_policy: ${user.run_dir}/swingup_openloop_policy.pth
