defaults:
  - user: user2
  - plant_param: param1

hydra:
  run:
    dir: ${user.run_dir}
  sweep:
    dir: ${user.run_dir}

device: "cuda"
seed: 123

dataset:
  load_path: ${user.dataset_load_path}
  sample_size: 1000000

train:
  wandb:
    enabled: ${user.wandb_enabled}
    project: score_po
    dir: ${user.run_dir}
    name: ${now:%Y.%m.%d-%H.%M.%S}_cartpole
    entity: ${user.wandb_entity}
  adam:
    lr: 1e-3
    epochs: 300
    batch_size: 1024
  dataset_split: [0.8, 0.2]
  save_best_model: checkpoint/checkpoint.pth
  load_ckpt: null
  device: "cuda"

train_model: True
