defaults:
  - user: hongkai

hydra:
  run:
    dir: ${user.run_dir}

device: "cuda"
seed: 123

dataset:
  load_path: ${user.dataset_load_path}

train:
  wandb:
    enabled: ${user.wandb_enabled}
    project: score_po
    name: ${now:%Y.%m.%d-%H.%M.%S}_cartpole_score
    entity: ${user.wandb_entity}
  lr: 1e-3
  epochs: 500
  batch_size: 1024