defaults:
  - user: hongkai
  - plant_param: param1

hydra:
  run:
    dir: ${user.run_dir}
  sweep:
    dir: ${user.run_dir}

device: "cuda"
seed: 123

dataset:
  load_path: ${user.dataset_load_path}

train:
  wandb:
    enabled: ${user.wandb_enabled}
    project: score_po
    name: ${now:%Y.%m.%d-%H.%M.%S}_cartpole_score
    dir: ${user.run_dir}
    entity: ${user.wandb_entity}
  adam:
    lr: 1e-3
    epochs: 100
    batch_size: 2048
  dataset_split: [0.8, 0.2]
  save_best_model: ${user.save_score_ckpt}
  device: "cuda"
  sigma: 0.01
  xu: True