defaults:
  - user: hongkai
  - plant_param: param1

hydra:
  run:
    dir: ${user.run_dir}
  sweep:
    dir: ${user.run_dir}

device: "cuda"
seed: 123

single_shooting: True

trj:
  wandb:
    enabled: ${user.wandb_enabled}
    project: score_po
    dir: ${user.run_dir}
    name: ${now:%Y.%m.%d-%H.%M.%S}_cartpole_swingup_cem
    entity: ${user.wandb_entity}
  T: 60
  std: 0.05
  lr: 1e-2
  max_iters: 20000
  save_best_model: ${user.save_swingup_trj}
  device: "cuda"
  load_ckpt: ${user.load_swingup_trj}
  saving_period: 100
  n_elite: 4
  batch_size: 10
  beta: 0.1

dynamics_load_ckpt: ${user.dynamics_load_ckpt}
dde_xu_load_ckpt: ${user.dde_xu_load_ckpt}