defaults:
  - user: hongkai

hydra:
  run:
    dir: ${user.run_dir}

device: "cuda"
seed: 123
nn_plant:
  dt: 0.05
  hidden_layers: [64, 64, 32]
  u_max: 80

policy:
  wandb:
    enabled: ${user.wandb_enabled}
    project: score_po
    dir: ${user.run_dir}
    name: ${now:%Y.%m.%d-%H.%M.%S}_cartpole_swingup
    entity: ${user.wandb_entity}

dynamics_load_ckpt: ${user.dynamics_load_ckpt}
load_swingup_policy: ${user.load_swingup_policy}
save_swingup_policy: ${user.save_swingup_policy}