defaults: 
  - user: user1

hydra:
  run:
    dir: ${user.run_dir}

device: "cuda"

N: 3 # data points.
x_range: 2.0 # range to query. [-x_range, x_range]
n_grid: 10000 # number of grid spots to plot.
sigma: 0.1 # perturbation std.
ensemble_size: 3

# Candidates: 51, 123, 48, 321
seed: 321
# Plotting scale.
scale_gp: 3.0
scale_ensemble: 40.0
scale_softmin: 0.4

scale_ensemble_plot: 100.0
scale_gp_plot: 8.0

ylim_top: 5
ylim_bottom: -4

nn_layers: [512, 512]

train:
  wandb:
    enabled: ${user.wandb_enabled}
    project: score_po
    dir: ${user.run_dir}
    name: ${now:%Y.%m.%d-%H.%M.%S}_admissibility_stability
    entity: ${user.wandb_entity}
  adam:
    lr: 1e-3
    epochs: 1000
    batch_size: 32
  dataset_split: null  
  save_best_model: checkpoint.pth
  load_ckpt: null
  device: "cuda"


