device: "cuda"

N: 3 # data points.
x_range: 2.0 # range to query. [-x_range, x_range]
n_grid: 10000 # number of grid spots to plot.
sigma: 0.05 # perturbation std.

seed: 123
nn_layers: [64, 64, 64, 64, 64, 64]

train:
  wandb:
    enabled: True
    project: null
    entity: null
  adam:
    lr: 1e-3
    epochs: 2000
    batch_size: 512
  device: "cuda"
  save_best_model: null
  dataset_split: null
