defaults: 
  - user: hongkai

hydra:
  run:
    dir: ${user.run_dir}

device: "cuda"
seed: 123

train:
  wandb:
    enabled: ${user.wandb_enabled}
    project: score_po
    name: ${now:%Y.%m.%d-%H.%M.%S}_uniform1d_score
    dir: ${user.run_dir}
    entity: ${user.wandb_entity}
  adam:
    lr: 1e-3
    epochs: 30
    batch_size: 1024 
  dataset_split: [0.8, 0.2]
  save_best_model: ${user.run_dir}/checkpoint.pth
  device: "cuda"