defaults:
  - user: terry

hydra:
  run:
    dir: ${user.run_dir}


nn_layers: [256, 256, 256, 256]
nn_layers_policy: [128, 128]
env_name: ${user.env_name}
sigma: 0.05

cost_weights: ${user.cost_weights}
dynamics_weights: ${user.dynamics_weights}
score_weights: ${user.score_weights}
policy_weights: ${user.policy_weights}

# Train parameters
policy:
  T: 200
  x0_upper: [0.5, 0.5] # x0_upper = x0_lower for trajopt.
  x0_lower: [-0.5, -0.5]
  batch_size: 256
  std: 0.1
  lr: 1e-2
  max_iters: 300
  save_best_model: checkpoint_policy_${user.env_name}.pth
  load_ckpt: null
  device: "cuda"
  first_order: False
  beta: 0.0

  wandb:
    enabled: ${user.wandb_enabled}
    project: score_po
    dir: ${user.run_dir}
    name: ${now:%Y.%m.%d-%H.%M.%S}_d4rl_${user.env_name}_${policy.beta}
    entity: ${user.wandb_entity}
