defaults:
  - user: user1

hydra:
  run:
    dir: ${user.run_dir}


nn_layers: [256, 256, 256, 256]
nn_layers_policy: [128, 128]
env_name: ${user.env_name}
sigma: 0.05
trial: 0

cost_weights: ${user.run_dir}/checkpoint_cost_${env_name}.pth
score_weights: ${user.run_dir}/checkpoint_score_xux_log_1_2_${env_name}.pth

warm_start: True

trj:
  T: 20
  x0: [0.8, 0.2]
  xT: [-0.8, 0.2]
  batch_size: 1 # 1 for trajopt.
  lr: 1e-2
  max_iters: 2000
  save_best_model: null
  saving_period: null
  load_ckpt: null
  device: "cuda"
  beta: 100.0

  wandb:
    enabled: ${user.wandb_enabled}
    project: score_po
    dir: ${user.run_dir}
    name: ${now:%Y.%m.%d-%H.%M.%S}
    entity: ${user.wandb_entity}
