defaults:
  - user: terry

hydra:
  run:
    dir: ${user.run_dir}
  sweep:
    dir: /home/terry/Documents/score_po_data/d4rl_sweep8

nn_layers: [256, 256, 256, 256]
nn_layers_policy: [128, 128]
env_name: ${user.env_name}

cost_weights: ${user.run_dir}/checkpoint_cost_${env_name}.pth
score_weights: ${user.run_dir}/checkpoint_score_xu_41_${env_name}.pth
dynamics_weights: ${user.run_dir}/checkpoint_dynamics_sim_4_${env_name}.pth

warm_start: True # No warm start noise
beta: 0.12 # Anneal to 0.09
T: 14
lr: 2e-1
max_iters: 100

trj:
  T: ${T}
  x0: [0.8, 0.2]
  xT: [-0.8, 0.2]
  batch_size: 1 
  lr: ${lr} 
  max_iters: ${max_iters}
  save_best_model: null
  saving_period: null
  load_ckpt: null
  device: "cuda"
  beta: ${beta}

  wandb:
    enabled: ${user.wandb_enabled}
    project: score_po
    dir: ${user.run_dir}
    name: ${now:%Y.%m.%d-%H.%M.%S}
    entity: ${user.wandb_entity}
