defaults:
  - user: terry

hydra:
  run:
    dir: ${user.run_dir}

dataset_size: 100000
dataset_dir: ${user.dataset_dir}

# Choose between "world" or "body". When set to "body", we collect
# data in the body frame and set the box pose to [0, 0, 0].
frame: "body" # choose between "world" or "body".

# noise to inject on keypoints.
noise_std: 0.0