defaults:
  - user: user1

hydra:
  run:
    dir: ${user.run_dir}

dataset_dir: ${user.dataset_dir}
dynamic_weights: "~/Documents/score_po_data/box_keypoints/checkpoint_dynamics.pth"

train:
  wandb:
    enabled: ${user.wandb_enabled}
    project: score_po_keypts
    dir: ${user.run_dir}
    name: ${now:%Y.%m.%d-%H.%M.%S}_keypoint_dynamics
    entity: ${user.wandb_entity}  
  adam:
    lr: 1e-3
    epochs: 1000
    batch_size: 1024
  dataset_split: [0.99, 0.01]
  save_best_model: checkpoint_dynamics.pth
  load_ckpt: null
  device: "cuda"  
