defaults:
  - user: terry

hydra:
  run:
    dir: ${user.run_dir}

dataset_dir: ${user.dataset_dir}
score_weights: "/home/terry/Documents/score_po_data/box_keypoints/checkpoint_score_xu.pth"
max_iters: 1000
step_size: 1e-4

train:
  wandb:
    enabled: ${user.wandb_enabled}
    project: score_po_keypts
    dir: ${user.run_dir}
    name: ${now:%Y.%m.%d-%H.%M.%S}_keypoint_score
    entity: ${user.wandb_entity}  
  adam:
    lr: 1e-3
    epochs: 1000
    batch_size: 1024
  dataset_split: null    
  save_best_model: checkpoint_score_xu.pth
  load_ckpt: null
  device: "cuda"  
