defaults:
  - user: terry

hydra:
  run:
    dir: ${user.run_dir}


nn_layers: [128, 128, 128, 128]
dataset_dir: ${user.dataset_dir}
sigma: 0.05

# Train parameters
train:
  wandb:
    enabled: ${user.wandb_enabled}
    project: score_po
    dir: ${user.run_dir}
    name: ${now:%Y.%m.%d-%H.%M.%S}_keypoint_score
    entity: ${user.wandb_entity}  
  adam:
    lr: 1e-3
    epochs: 3000
    batch_size: 2048
  dataset_split: null    
  save_best_model: checkpoint_score_hole_augment.pth
  load_ckpt: null
  device: "cuda"  
