defaults:
  - user: user1

hydra:
  run:
    dir: ${user.run_dir}

policy:
  T: 20
  x0_upper: [0.8, 0.8] # x0_upper = x0_lower for trajopt.
  x0_lower: [-0.8, -0.8]
  batch_size: 1024 # 1 for trajopt.
  std: 1e-2
  lr: 1e-3
  max_iters: 200
  save_best_model: checkpoint.pth
  load_ckpt: null
  device: "cpu"
  first_order: False
  beta: 100.0

  wandb:
    enabled: ${user.wandb_enabled}
    project: score_po
    dir: ${user.run_dir}
    name: ${now:%Y.%m.%d-%H.%M.%S}_distance_likelihood
    entity: ${user.wandb_entity}

cost:
  Q: [1, 1]
  R: [1, 1]
  Qd: [100, 100]
  xd: [-0.7, -0.2]
