defaults:
  - user: terry

hydra:
  run:
    dir: ${user.run_dir}

nn_layers: [512, 512]
dataset_size: 100000

train:
  wandb:
    enabled: ${user.wandb_enabled}
    project: score_po
    dir: ${user.run_dir}
    name: ${now:%Y.%m.%d-%H.%M.%S}_cartpole
    entity: ${user.wandb_entity}
  adam:
    lr: 1e-3
    epochs: 1000
    batch_size: 1024
  dataset_split: [0.99, 0.01]
  save_best_model: checkpoint_xux.pth
  load_ckpt: null
  device: "cuda"
