defaults:
  - user: user1

hydra:
  run:
    dir: ${user.run_dir}

policy:
  T: 20
  x0_upper: [0.3, 0.2] # x0_upper = x0_lower for trajopt.
  x0_lower: [0.3, 0.2]
  batch_size: 128 # 1 for trajopt.
  std: 0.0
  lr: 1e-3
  max_iters: 100
  save_best_model: checkpoint.pth
  load_ckpt: null
  device: "cpu"

  wandb:
    enabled: ${user.wandb_enabled}
    project: score_po
    dir: ${user.run_dir}
    name: ${now:%Y.%m.%d-%H.%M.%S}_distance_likelihood
    entity: ${user.wandb_entity}

cost:
  Q: [1, 1]
  R: [1e-1, 1e-1]
  Qd: [100, 100]
  xd: [0, 0]
