dt: 0.05
num_models: 6
hidden_layers:
  - [64, 64, 32]
  - [64, 64, 32]
  - [64, 64, 32]
  - [64, 64, 32]
  - [64, 64, 32]
  - [64, 64, 32]
u_max: 80
x_lo: 
 - -5
 - ${np.pi:-1}
 - -8
 - -12
x_up:
  - 5 
  - ${np.pi:1.5}
  - 8 
  - 12 